# Site Settings
name: Le 7eptième Œil
title: Le 7eptième Œil | L'œil qui voit tout le Cinéma
description: >- # this means to ignore newlines until "baseurl:"
  L'œil qui voit tout le Cinéma
tags:
  - blog
  - cinema
  - critique
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: Notre équipe
    url: /staff
  - title: À Propos
    url: /about
  - title: Nous contacter
    url: /contact
email: le7eptiemeoeil@gmail.com

# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mqknkwel
# Localization
date_format: "%d %B %Y"
language: "fr"

# Social Media Settings
# Remove the item if you don't need it
twitter_username:
facebook_username:  
instagram_username: le7eptiemeoeil
medium_username: 
threads_username: le7eptiemeoeil
letterboxd_username:
serializd_username:

# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://poetic-buttercream-0d3e15.netlify.app" # the base hostname & protocol for your site
google_analytics: "G-XXXXXXXX"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Localization
translations:
  text:
    new_post: "Article récent"
    see_also: "Voir aussi"
    search: "Recherche"
    author: "Auteur"
    share: "Partager"
    comments: "Commentaires"
  button:
    read_now: "Lire l’article"
    share_on_twitter: "Partager sur X"
    share_on_facebook: "Partager sur Facebook"
  pagination:
    page: "Page"
    of: "sur"
    next_page: "Page suivante"
    next_post: "Article suivant"
  recommendation:
    text: "Que diriez-vous de vous plonger dans un nouvel article ?"
    back_btn: "Retourner en haut de la page"
  error_404:
    title: "Woops ! Page introuvable :("
    message: "Il semblerait que la page que vous recherchez est hors ligne ou a été
    déplacée ailleurs."
    image_alt: "404 - Page not found"
  contact:
    title: "Nous contacter"
    subject: "Nouveau message !"
    submit_btn: "Envoyer"
    placeholders:
      name: "Nom"
      email: "Adresse e-mail"
      message: "Message"
    errors:
      locale: "fr"
      empty_name: "Veuillez entrer votre nom"
      empty_email: "Veuillez entrer une adresse e-mail"
      invalid_email: "Veuillez entrer une adresse e-mail valide"
      empty_message: "Le message ne peut pas être vide"
    after_send:
      title: "Message envoyé !"
      message: "Nous vous remercions de nous avoir contactés et nous vous répondrons
      dès que possible."

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
show_get_theme_btn: false
use_logo: true

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 8
  permalink: '/page/:num/'
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: 'fr_FR' 

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate-v2

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2
