# Site Settings
title: Sumit Kumar Jha
email: youremail@xyz.com
description: Sumit's official blog site.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "Sumit-Kumar-Jha.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
logo: logo.jpg

# User Settings
username: Sumit
user_description: Automation Consultant.
disqus_username: somusumit

# Social Media
# Remove the item if you don't need it
github_username: Sumit-Kumar-Jha
facebook_username: facebook_username
twitter_username: somusumit
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
