backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
site_url: https://poetic-buttercream-0d3e15.netlify.app/
logo_url: https://poetic-buttercream-0d3e15.netlify.app/assets/img/certicon.svg
collections:
  - label: "Rubriques"
    name: "categories"
    folder: "category"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    preview_path: "category/{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "category"
      - label: "Nom"
        name: "title"
        widget: "string"
      - label: "Slug"
        name: "slug"
        widget: "hidden"
        default: "{{slug}}"
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
  - label: "Publications"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        format: "DD-MM-YYYY HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Titre"
        name: "title"
        widget: "string"
      - label: "Sous-titre"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Description"
        name: "description"
        hint: "Sera utilisé sur l'ensemble du site et pour le reférencement web"
        widget: "string"
      - label: "Photo de couverture"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: false
      - label: "Photo de couverture optimisée"
        name: "optimized_image"
        widget: "image"
        allow_multiple: false
        required: false
        hint: "La version optimisée sera affichée sur la page d'accueil"
      - label: "Rubrique"
        name: "category"
        widget: "relation"
        collection: "categories"
        searchFields: ["title"]
        valueField: "slug"
        displayFields: ["title"]
      - label: "Tags"
        name: "tags"
        hint: "Separate with commas. These will also be used as keywords for search engines."
        widget: "list"
      - label: "Auteur"
        name: "author"
        widget: "relation"
        collection: "authors"
        displayFields: [display_name]
        searchFields: [display_name]
        valueField: "name"
      - label: "Activer la pagination (longs articles)"
        name: "paginate"
        widget: "boolean"
        default: false
      - label: "Article"
        name: "body"
        widget: "markdown"
  - label: "Pages"
    name: "pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Afficher dans le menu"
        name: "menu"
        widget: "boolean"
        default: true
      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        format: "DD-MM-YYYY HH:mm:ss"
      - label: "Nom de la page"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{slug}}/"
      - label: "Description"
        name: "description"
        hint: "Cette description sera utilisée par les moteurs de recherche."
        widget: "string"
        required: false
      - label: "Mots-clés"
        name: "tags"
        hint: "Séparez-les par des virgules. Seront également utilisés comme mots-clés par les moteurs de recherche."
        widget: "list"
        required: false
      - label: "Contenu"
        name: "body"
        widget: "markdown"
  - label: "Redacteurs"
    name: "authors"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "author"
      - label: "Photo"
        name: "photo"
        widget: "image"
        required: false
        hint: "Veuillez utiliser une image carrée (1:1) pour un rendu optimal"
      - label: "Pseudo"
        name: "name"
        widget: "string"
      - label: "Nom complet"
        name: "display_name"
        hint: "Le nom que vous voulez utiliser pour signer vos publications"
        widget: "string"
      - label: "Rôle/Poste occupé"
        name: "position"
        widget: "string"
        required: false
      - label: "Bio"
        name: "bio"
        widget: "text"
      - label: "Nom d'utilisateur GitHub"
        name: "github_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Facebook"
        name: "facebook_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Twitter"
        name: "twitter_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Instagram"
        name: "instagram_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur LinkedIn"
        name: "linkedin_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Medium"
        name: "medium_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Threads"
        name: "threads_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Letterboxd"
        name: "letterboxd_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur Serializd"
        name: "serializd_username"
        widget: "string"
        required: false
      - label: "Nom d'utilisateur MyAnimeList"
        name: "myanimelist_username"
        widget: "string"
        required: false
  - label: "Paramètres"
    name: "settings"
    editor:
      preview: false
    delete: false
    files:
      - label: "Paramètres du site"
        name: "site"
        file: "src/yml/site.yml"
        fields:
          - label: "Nom du site"
            name: "name"
            widget: "string"
          - label: "Titre du site"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            hint: "Cette description sera utilisée par les moteurs de recherche."
            widget: "string"
            required: false
          - label: "Mots-clés"
            name: "tags"
            hint: "Séparez-les par des virgules. Seront également utilisés comme mots-clés par les moteurs de recherche."
            widget: "list"
            required: false
          - label: "Mettre en avant la dernière publication"
            name: "show_hero"
            widget: "boolean"
            default: true
          - label: "Nombre de posts par page"
            name: "paginate"
            widget: "number"
            valueType: "int"
            required: false
            hint: "Laisser vide pour désactiver la pagination"
          - label: "Menu"
            name: "menu"
            widget: "list"
            required: false
            fields:
              - label: "Titre"
                name: "title"
                widget: "string"
                hint: "Texte à afficher dans le menu"
              - label: "URL"
                name: "url"
                widget: "string"
                hint: "Ex: /contact"
          - label: "E-mail"
            name: "email"
            widget: "string"
            hint: "Laisser vide pour désactiver la page de contact"
            required: false
      - label: "Comptes sociaux"
        name: "social"
        file: "src/yml/social.yml"
        fields:
          - label: "Nom d'utilisateur GitHub"
            name: "github_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Facebook"
            name: "facebook_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Twitter"
            name: "twitter_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Instagram"
            name: "instagram_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur LinkedIn"
            name: "linkedin_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Medium"
            name: "medium_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Threads"
            name: "threads_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Letterboxd"
            name: "letterboxd_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur Serializd"
            name: "serializd_username"
            widget: "string"
            required: false
          - label: "Nom d'utilisateur MyAnimeList"
            name: "myanimelist_username"
            widget: "string"
            required: false
      - label: "Thème"
        name: "theme"
        file: "src/yml/theme.yml"
        fields:
          - label: "Couleur du thème"
            name: "themeColor"
            widget: "color"
            default: "#ff0a16"
          - label: "Couleur primaire sombre"
            name: "primaryDark"
            widget: "color"
            default: "#141414"
          - label: "Couleur d'accentuation sombre"
            name: "accentDark"
            default: "#ffffff"
            widget: "color"
          - label: "Gris clair"
            name: "lightGray"
            widget: "color"
            default: "#f2f2f2"
          - label: "Couleur du texte"
            name: "texts"
            widget: "color"
            default: "#333333"
      - label: "Publications"
        name: "posts"
        file: "src/yml/posts.yml"
        fields:
          - label: "Afficher la barre de progression de lecture"
            name: "show_time_bar"
            widget: "boolean"
            default: true
          - label: "Suggestion d'article avant de quitter le site"
            name: "show_modal_on_exit"
            widget: "boolean"
            default: false
          - label: "Suggestion en fin d'article"
            name: "show_modal_on_finish_post"
            widget: "boolean"
            default: false
          - label: "Affichage en deux colones"
            name: "two_columns_layout"
            widget: "boolean"
            default: true
      - label: "Traductions"
        name: "translations"
        file: "src/yml/translations.yml"
        fields:
          - label: "Texts"
            name: "texts"
            widget: "object"
            fields:
              - label: "New Post"
                name: "new_post"
                widget: "string"
                required: false
              - label: "See also"
                name: "seel_also"
                widget: "string"
                required: false
              - label: "Search"
                name: "search"
                widget: "string"
                required: false
              - label: "Share"
                name: "share"
                widget: "string"
                required: false
              - label: "Comments"
                name: "comments"
                widget: "string"
                required: false
          - label: "Buttons"
            name: "button"
            widget: "object"
            fields:
              - label: "Read Now"
                name: "read_now"
                widget: "string"
                required: false
              - label: "Share on Twitter"
                name: "share_on_twitter"
                widget: "string"
                required: false
              - label: "Share on Facebook"
                name: "share_on_facebook"
                widget: "string"
                required: false
          - label: "Pagination"
            name: "pagination"
            widget: "object"
            fields:
              - label: "Page"
                name: "page"
                widget: "string"
                required: false
              - label: "of"
                name: "of"
                widget: "string"
                required: false
              - label: "Next Page"
                name: "next_page"
                widget: "string"
                required: false
              - label: "Next Post"
                name: "next_post"
                widget: "string"
                required: false
          - label: "Recommendation"
            name: "recommendation"
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
                required: false
              - label: "Go back to top"
                name: "back_btn"
                widget: "string"
                required: false
          - label: "Error 404"
            name: "error_404"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: false
              - label: "Message"
                name: "message"
                widget: "string"
                required: false
              - label: "Image Alt"
                name: "image_alt"
                widget: "string"
                required: false
          - label: "Contact Page"
            name: "contact"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: false
              - label: "Email Subject Title"
                name: "subject"
                widget: "string"
                required: false
              - label: "Submit Button Label"
                name: "submit_btn"
                widget: "string"
                required: false
              - label: "Fields Placeholder"
                name: "placeholders"
                widget: "object"
                fields:
                  - label: "Your Name"
                    name: "name"
                    widget: "string"
                    required: false
                  - label: "Your Email"
                    name: "email"
                    widget: "string"
                    required: false
                  - label: "Your Message"
                    name: "message"
                    widget: "string"
                    required: false
              - label: "Fields Error"
                name: "errors"
                widget: "object"
                fields:
                  - label: "Locale"
                    name: "locale"
                    widget: "string"
                    default: "en"
                    hint: "Ex: en"
                  - label: "Empty Name"
                    name: "empty_name"
                    widget: "string"
                    hint: "Ex: Insert your name"
                    required: false
                  - label: "Empty Email"
                    name: "empty_email"
                    widget: "string"
                    hint: "Ex: Insert your email"
                    required: false
                  - label: "Invalid Email"
                    name: "invalid_email"
                    widget: "string"
                    hint: "Ex: Email is invalid"
                    required: false
                  - label: "Empty Message"
                    name: "empty_message"
                    widget: "string"
                    hint: "Ex: Insert your message"
                    required: false
              - label: "Contact Feedback Page"
                name: "after_send"
                widget: "object"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    hint: "Ex: Message sent!"
                    required: false
                  - label: "Text"
                    name: "message"
                    widget: "string"
                    hint: "Ex: Thank you for reaching us."
                    required: false
      - label: "Avancé"
        name: "advanced"
        file: "src/yml/advanced.yml"
        fields:
          - label: "URL de base"
            name: "baseurl"
            widget: "string"
            hint: "Le chemin d'accès du site, ex: /blog"
          - label: "URL"
            name: "url"
            widget: "string"
            hint: "Le nom de domaine et le protocole du site, ex: https://rossener.com"
          - label: "Google Analytics ID"
            name: "google_analytics"
            widget: "string"
            required: false
          - label: "Langue"
            name: "language"
            widget: "string"
            hint: "Langue du contenu du site, ex: pt-BR, en, fr"
          - label: "Dossier des rubriques"
            name: "categories_folder"
            widget: "string"
            hint: "Dossier dans lequel se trouvent les rubriques du site. Ex: category"
            required: false
          - label: "URL redirection de contact"
            name: "sent_message_url"
            hint: "URL vers laquelle l'utilisateur sera redirigé après avoir soumis le formulaire de contact. Ex: /contact/message-sent/"
            required: false


